schema_version = 7

[workspace]
name = 'postoffice'
id = '53b4b8e5c2289f98d8b4b7537f94ae3facbb03934dc5363e4608bd27703c2837'

[blob_store]
type = 'local'

[key]
[key.alpine-signing]
algorithm = 'apk-rsa4096'
usage = 'sign'
fingerprint = 'c0006940f42b2c7ea44c95f91275f5b5c1f5002f'
created_at = '2026-07-29T07:41:50Z'
expires_at = '2028-07-28T07:41:50Z'
public_key = 'keys/alpine-signing.rsa.pub'
public_key_sha256 = '8f9d1c0bf08a6d186d1ae2add17c12883f0014d457826385452b6d9e512ab5b6'
public_armor = 'keys/alpine-signing.rsa.pub'
public_armor_sha256 = '8f9d1c0bf08a6d186d1ae2add17c12883f0014d457826385452b6d9e512ab5b6'

[key.alpine-signing.ref]
backend = 'file'
id = '53b4b8e5c2289f98d8b4b7537f94ae3facbb03934dc5363e4608bd27703c2837/alpine-signing'

[key.archive-signing]
algorithm = 'openpgp-rsa4096'
usage = 'sign'
fingerprint = '1e00d64dcafdff06dc70acefdf1c620e53596d7f'
created_at = '2026-07-28T22:17:22Z'
expires_at = '2028-07-27T22:17:22Z'
public_key = 'keys/archive-signing.gpg'
public_key_sha256 = '7ee8e8b709c85c7de020bac4ebf0d9e1e5369f8c6c0d80da8b551844a44fcd7a'
public_armor = 'keys/archive-signing.asc'
public_armor_sha256 = 'e812747241b2a67c891da6d309d970826a48c341623f5836611b7c81fc0ce427'

[key.archive-signing.ref]
backend = 'file'
id = '53b4b8e5c2289f98d8b4b7537f94ae3facbb03934dc5363e4608bd27703c2837/archive-signing'

[repo]
[repo.alpine]
format = 'apk'
lock = 'repos/alpine.lock.toml'
visibility = 'public'
gate = 'auto'
signing_keys = ['alpine-signing']
signing_keyring = 'keys/alpine-archive-keyring.gpg'
track = 'stable'
architectures = ['x86_64', 'aarch64']

[repo.alpine.host]
type = 'local'
path = 'docs/alpine'

[repo.apt]
format = 'deb'
lock = 'repos/apt.lock.toml'
visibility = 'public'
gate = 'auto'
signing_keys = ['archive-signing']
signing_keyring = 'keys/archive-signing.gpg'
track = 'stable'
suite = 'stable'
component = 'main'
architectures = ['amd64', 'arm64']

[repo.apt.host]
type = 'local'
path = 'docs/apt'

[repo.charts]
format = 'helm'
lock = 'repos/charts.lock.toml'
visibility = 'public'
gate = 'auto'
track = 'stable'

[repo.charts.host]
type = 'local'
path = 'docs/charts'

[repo.releases]
format = 'raw'
lock = 'repos/releases.lock.toml'
visibility = 'public'
gate = 'auto'
track = 'stable'

[repo.releases.host]
type = 'local'
path = 'docs/releases'

[repo.yum]
format = 'rpm'
lock = 'repos/yum.lock.toml'
visibility = 'public'
gate = 'auto'
signing_keys = ['archive-signing']
signing_keyring = 'keys/yum-archive-keyring.gpg'
track = 'stable'

[repo.yum.host]
type = 'local'
path = 'docs/yum'
