schema_version = 2
repository = 'alpine'

[[package_version]]
package = 'snailmail'
version = '0.0.9-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.9-r1_aarch64.apk'
architecture = 'aarch64'
size = 7205576
md5 = 'b36e61fb8f5d7cdc91aa60ff50934f30'
sha1 = 'c4fb8f78c84eb717197f5ce0f0be15d4cdbd052b'
sha256 = 'a9779a91cd6b54c0aae5b6135dc1bb24fc8cb8c653d0e475d7924b8f0474ba75'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9-r1_aarch64.apk'

[[package_version.blob]]
filename = 'snailmail_0.0.9-r1_x86_64.apk'
architecture = 'x86_64'
size = 8112482
md5 = 'be72d68a87a4b1881d66caa732fe80c3'
sha1 = '6164985d6f90cdc39c089119002a5894595921b6'
sha256 = 'fd44a4dbe446f78b99104fb8fd1b5dd60c928d7e0a4891b17dc0978edbbba98c'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9-r1_x86_64.apk'

[[package_version]]
package = 'snailmail'
version = '0.1.0-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.0-r1_aarch64.apk'
architecture = 'aarch64'
size = 7209965
md5 = 'ff706d60e1a6b35006a6c9b6043a414f'
sha1 = '4aad38d776eda3d623cc27a091546b64ef7660a4'
sha256 = '00858adf70ed8059767c7c2498fed4f901d9655c9b0cf07b5b93cc6824e93170'
added = '2026-07-29T09:35:14Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.0/snailmail_0.1.0-r1_aarch64.apk'

[[package_version.blob]]
filename = 'snailmail_0.1.0-r1_x86_64.apk'
architecture = 'x86_64'
size = 8117970
md5 = '5566ffa47a4b5455675f422d33121706'
sha1 = '40a6f9ccb8ef35b63886f3476c573966e703b368'
sha256 = '824719a0faebc1267cc5daabbec3a80f9222224e6a5884f61193b8cdb590157f'
added = '2026-07-29T09:35:15Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.0/snailmail_0.1.0-r1_x86_64.apk'

[[package_version]]
package = 'snailmail'
version = '0.1.1-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.1-r1_aarch64.apk'
architecture = 'aarch64'
size = 7231494
md5 = 'beae45c171fedb6075672536f7ee5ee3'
sha1 = 'f2b79ac815d89724df6c5774b3f1ff2f871bde82'
sha256 = '19542827500773fd8c588cf45beae593c52ca8a62176f3e3f8fb6c593b8bcfc1'
added = '2026-07-29T11:14:58Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.1/snailmail_0.1.1-r1_aarch64.apk'

[[package_version.blob]]
filename = 'snailmail_0.1.1-r1_x86_64.apk'
architecture = 'x86_64'
size = 8148502
md5 = 'd794acd43c579ee15be7065455954509'
sha1 = '5042c0722d4ff74082051e6cea6f0aeadad17356'
sha256 = 'e9976978b885b02ab1270364256dca221be2f90d7464ccefb45da5f0c49da306'
added = '2026-07-29T11:14:58Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.1/snailmail_0.1.1-r1_x86_64.apk'

[[package_version]]
package = 'snailmail'
version = '0.1.2-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.2-r1_aarch64.apk'
architecture = 'aarch64'
size = 7246852
md5 = '80af8e5a460201cfd62675d5aefe42cf'
sha1 = '29fd3fc62ddffef9af5f641cecb067f276da7f0d'
sha256 = 'd783844117887f432481251e9b0bda2d00461f798df39aaba9c95672ea6c58d2'
added = '2026-07-29T12:40:50Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.2/snailmail_0.1.2-r1_aarch64.apk'

[[package_version.blob]]
filename = 'snailmail_0.1.2-r1_x86_64.apk'
architecture = 'x86_64'
size = 8168274
md5 = 'aedc615fe8544db78c763361ef1a00c5'
sha1 = '916ecd7a9f808400aa45babe7d9e69fc4ca2076c'
sha256 = '673dc7efacd9fb4b7da3e06cc249bc8f8aa4b1011474ad5c3946215297a02427'
added = '2026-07-29T12:40:51Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.2/snailmail_0.1.2-r1_x86_64.apk'

[[package_version]]
package = 'snailmail'
version = '0.1.3-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.3-r1_aarch64.apk'
architecture = 'aarch64'
size = 7257203
md5 = '78e50fecea4ca8ee05ea847b520be1a1'
sha1 = '77bc0766be8a25205d7c14ddfbbbbed7dff9a8a5'
sha256 = 'fe00835cefd1f87f8a71ce89a739fb782c414fab1c7273062d70a86538c7bb2e'
added = '2026-07-29T14:58:22Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.3/snailmail_0.1.3-r1_aarch64.apk'

[[package_version.blob]]
filename = 'snailmail_0.1.3-r1_x86_64.apk'
architecture = 'x86_64'
size = 8160888
md5 = '6f820de0ddb2adf5ea8e0dfb2360a1e4'
sha1 = '03c8ebcada7b3c7d4df28e8064ac5a833ae2d308'
sha256 = '96d1b5e06d6ad749cad09ae90678cb7fb7615d930a6248d763d3a9e348338e8f'
added = '2026-07-29T14:58:23Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.3/snailmail_0.1.3-r1_x86_64.apk'

[[package_version]]
package = 'snailmail'
version = '0.1.4-r1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.4-r1_aarch64.apk'
architecture = 'aarch64'
size = 7378379
sha256 = '8910729c4433cec496d84259109c3b5a7c4fe200e09c40b02e403857215ba424'
added = '2026-07-30T21:43:59Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.4/snailmail_0.1.4-r1_aarch64.apk'
provenance = 'operator'

[[package_version.blob]]
filename = 'snailmail_0.1.4-r1_x86_64.apk'
architecture = 'x86_64'
size = 8284888
sha256 = '2f08620ff8fd9b91821e76d213e875d027325f458f0237942b46f3675b40cd6c'
added = '2026-07-30T21:43:59Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.4/snailmail_0.1.4-r1_x86_64.apk'
provenance = 'operator'

[[package_version]]
package = 'ttysvg'
version = '0.1.2'
state = 'draft'

[[package_version.blob]]
filename = 'ttysvg_0.1.2_aarch64.apk'
architecture = 'aarch64'
size = 1248295
md5 = '531c12d1328b57a507ff9edfba2fc21e'
sha1 = '1050bf010b1938dbc4eec64e21d3645d250406f9'
sha256 = 'f0fdcac3d0245f8d029bea24b17a5c31f699c0e8c125ef124f3e53b801e5eb7f'
added = '2026-07-29T10:16:55Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/ttysvg/releases/download/v0.1.2/ttysvg_0.1.2_aarch64.apk'

[[package_version.blob]]
filename = 'ttysvg_0.1.2_x86_64.apk'
architecture = 'x86_64'
size = 1373446
md5 = 'e64f2a1524cb088cba995d71a1154252'
sha1 = '51adc98f238351b81f730fd99fc213906e94735e'
sha256 = 'c0f2cebc29b25aa96bcfe44bbdea4bcdd9e6719811c1cc1a0235ae8430700fa0'
added = '2026-07-29T10:16:54Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/ttysvg/releases/download/v0.1.2/ttysvg_0.1.2_x86_64.apk'

[[placement]]
package = 'snailmail'
version = '0.0.9-r1'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.0-r1'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.1-r1'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.2-r1'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.3-r1'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.4-r1'
track = 'stable'

[[placement]]
package = 'ttysvg'
version = '0.1.2'
track = 'stable'
