schema_version = 2
repository = 'apt'

[[package_version]]
package = 'snailmail'
version = '0.0.3-1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.3-1_amd64.deb'
architecture = 'amd64'
size = 6071936
md5 = '0f79202c49b0d008bb3b444a518001d8'
sha1 = '89177a881d02deb1707c3b89834e8d02ce9465ee'
sha256 = '611a4dd5c98f61c90a4e7b73f0f958b3751dd37a59efc10c131ef65dbd8d560d'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3-1_amd64.deb'

[[package_version.blob]]
filename = 'snailmail_0.0.3-1_arm64.deb'
architecture = 'arm64'
size = 5339914
md5 = '6b0efc8bb66d2b3fa74d35542284e5aa'
sha1 = 'ff92c808bc014e4129eb97b1b2e820d672fffa6b'
sha256 = '7963ba3b968e977c49d6f69cbde0b97f7ad480d20ba04be09e71b3bb8befd6a1'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3-1_arm64.deb'

[[package_version]]
package = 'snailmail'
version = '0.0.5-1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.5-1_amd64.deb'
architecture = 'amd64'
size = 6131920
md5 = '62293b80342043196e842bb06e41b5ef'
sha1 = '71cc3f2367d8aad034ea94d1683fd1f3522a90e0'
sha256 = '4409e7b62692fe50b8766284921a7e12a380cc52a05e55c549eceeb80c2948d8'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5-1_amd64.deb'

[[package_version.blob]]
filename = 'snailmail_0.0.5-1_arm64.deb'
architecture = 'arm64'
size = 5393304
md5 = 'acfd0f109a56e3c036286610697a1675'
sha1 = '9625050549c07fed5d27e78d872f8fee8581c7da'
sha256 = '13fdf17d1512a7b6db79a50740ac1bfab133dd5e481b850187ff2a7632f94a52'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5-1_arm64.deb'

[[package_version]]
package = 'snailmail'
version = '0.0.6-1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.6-1_amd64.deb'
architecture = 'amd64'
size = 6160702
md5 = '5799cf5ee34cd79c831f3be4fe2a597d'
sha1 = 'ff73d4d190eddce8df559b9bf66a3581dd024c7e'
sha256 = '712d69c73e8f09a7cc99b9f21c132b8e77d20c58b08ca648e66224e3ecc7d441'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6-1_amd64.deb'

[[package_version.blob]]
filename = 'snailmail_0.0.6-1_arm64.deb'
architecture = 'arm64'
size = 5417984
md5 = 'b5c529f07cb4d7527947dad6b2e65d6e'
sha1 = 'd09fe3bf53332307b78791cf8b7c589b514cff6b'
sha256 = 'b3f5b58c8431087d3289a68c11d0394573287e7210dc67b556bb0916fe3be18f'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6-1_arm64.deb'

[[package_version]]
package = 'snailmail'
version = '0.0.9-1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.9-1_amd64.deb'
architecture = 'amd64'
size = 7836236
md5 = 'dd5bb5c92bdee0a81dee70c18566967b'
sha1 = '262b440c47a17610adc33bbc6c8e43d37d2f0494'
sha256 = '4450aac00ce03985c80b54ef24e78aa8d2a0f7f8120b381af89700cd9ff873f6'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9-1_amd64.deb'

[[package_version.blob]]
filename = 'snailmail_0.0.9-1_arm64.deb'
architecture = 'arm64'
size = 7009540
md5 = 'cc300c7fc6c3f8f0684cab17392f7fe5'
sha1 = '641e879de8ba3b75bcc09d129a6657b62d935fb5'
sha256 = '8f913f9f4f5d216c89a8e3e8363bbae85dc460518e68c4bafda1d7f81b3dcddc'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9-1_arm64.deb'

[[package_version]]
package = 'snailmail'
version = '0.1.0-1'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.1.0-1_amd64.deb'
architecture = 'amd64'
size = 7852920
md5 = '144616b90f5aa1129a83c00ce2fc5a44'
sha1 = '12f538b67c76ef2dad263ecdb098faac205cd6a9'
sha256 = '83ad6a6851bd6eaf7e020cfb82afe101056070f2c1882c894d14d70f38541f3d'
added = '2026-07-29T09:35:11Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.0/snailmail_0.1.0-1_amd64.deb'

[[package_version.blob]]
filename = 'snailmail_0.1.0-1_arm64.deb'
architecture = 'arm64'
size = 7021598
md5 = '4f71832dc7345647eb4fffb94b759517'
sha1 = 'fe8613fff66f4e9077ed29390ae078e4f051119b'
sha256 = '3a0ed97f86de3d4b0bdea1068c35f440c8413a8830b785f79d718f49855bcebe'
added = '2026-07-29T09:35:12Z'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.1.0/snailmail_0.1.0-1_arm64.deb'

[[placement]]
package = 'snailmail'
version = '0.0.3-1'
track = 'stable'
distro = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.5-1'
track = 'stable'
distro = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.6-1'
track = 'stable'
distro = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.9-1'
track = 'stable'
distro = 'stable'

[[placement]]
package = 'snailmail'
version = '0.1.0-1'
track = 'stable'
distro = 'stable'
