schema_version = 2
repository = 'releases'

[[package_version]]
package = 'snailmail'
version = '0.0.3'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.3_darwin_amd64.tar.gz'
architecture = 'amd64'
size = 7702417
md5 = '6aee49aa7a321557d39796b130f74f09'
sha1 = 'cf330c25906dcd829fef0adb6a44827bf506078b'
sha256 = 'b6129231f07f2e9b19efa65fe96279cd965ea8958b28f69fbee22b3000048cba'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3_darwin_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.3_freebsd_amd64.tar.gz'
architecture = 'amd64'
size = 7529155
md5 = '19e6cc61c78c92e7e6e454d4e762abe1'
sha1 = 'c1e29b1b939a1cd8de00b868361e042288c23f9e'
sha256 = '96c9d4f1271cb5482ed7c8400c834fe1bd7107bbad99857c996cb7b1370cf37a'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3_freebsd_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.3_linux_amd64.tar.gz'
architecture = 'amd64'
size = 7599387
md5 = '2622b1e940d5d0290c5faf9dafb99995'
sha1 = '4006013b8b02bd53438208b2939329b43698d2da'
sha256 = '288ffbf00fec6ed630e99c804ef69441bd83ac6cf9ee29663f9886def613e8ac'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3_linux_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.3_darwin_arm64.tar.gz'
architecture = 'arm64'
size = 7033798
md5 = '695cfbbe5174e9093167b5a8c7175b54'
sha1 = 'db7030938dd1274c0e5dfb7c8a923632358b2bb6'
sha256 = '731839970f0721e02f6ebd04a86624cccfa39954c530c84aedb0aa8919369ced'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3_darwin_arm64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.3_linux_arm64.tar.gz'
architecture = 'arm64'
size = 6733834
md5 = '84b433194062454a662bc51da23692d4'
sha1 = 'f87f50e3ee57c4d2abf747580f2238fd02b462e7'
sha256 = 'ae0676e09fb158fd6a9c9b1b3cdd98358f29b42f7d2fd0dba82d3da276e107a2'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.3/snailmail_0.0.3_linux_arm64.tar.gz'

[[package_version]]
package = 'snailmail'
version = '0.0.5'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.5_darwin_amd64.tar.gz'
architecture = 'amd64'
size = 7782226
md5 = '47029645d0dcef5afe8a502599cfa542'
sha1 = '82e26a9ca859c2b79f6c499f3f41d37458464a89'
sha256 = '80470ccde25c1572f1557ccfe97d5a21c9e05d057fe1e1a0c44e22f68328fc01'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5_darwin_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.5_freebsd_amd64.tar.gz'
architecture = 'amd64'
size = 7606831
md5 = 'b614cf710c207fc7dd840ffa0ac24b65'
sha1 = '0a06c51c24d3f9fe902a38bfe6ac838175e70a35'
sha256 = '75be721d634d391789be46f962c94f4b5eb5f3ae89f24d6c8cf94b9148a7230e'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5_freebsd_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.5_linux_amd64.tar.gz'
architecture = 'amd64'
size = 7677328
md5 = 'dee2909fb7a9f48e1ad192ef5203fa1f'
sha1 = '2e53c506f04c2d55a2f768c78db51a4266250db6'
sha256 = '1727128648471fb0282a1e546a8345dba27bd8e8b2d864ee4b1fa220106df69c'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5_linux_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.5_darwin_arm64.tar.gz'
architecture = 'arm64'
size = 7106189
md5 = 'e916f1d0044b7cc5825a14d7b67f3728'
sha1 = '44a98a4be48788c417870df4e0e2997ea589bc2a'
sha256 = '2472b8bceb9732e4e6d9920fbfa329f3cbba473b85a0b9591ab846621540a3e4'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5_darwin_arm64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.5_linux_arm64.tar.gz'
architecture = 'arm64'
size = 6804089
md5 = '479949aa5a9201e07f3b1167d544ce63'
sha1 = '7134064528b08f6be121ca67191e9be3af1832da'
sha256 = '16e6b8dc94616d239ab4f9888386c04bcd3f362a5b44ffbc48d75a1462ebe40e'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.5/snailmail_0.0.5_linux_arm64.tar.gz'

[[package_version]]
package = 'snailmail'
version = '0.0.6'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.6_darwin_amd64.tar.gz'
architecture = 'amd64'
size = 7819337
md5 = '654a0ce883e62ea4685b4fdcf4714a8c'
sha1 = 'acf8f17fab765f5fc134e81b56eda19893430877'
sha256 = '472104ea0faca501cb37665761a57b523d32fcb7a4154bf7e3a4c1e7ca367416'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6_darwin_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.6_freebsd_amd64.tar.gz'
architecture = 'amd64'
size = 7641629
md5 = 'd42172f515507e005e4a5d206a47f6b4'
sha1 = '15750739a8f26d3478666f1787e688dab5040679'
sha256 = '10f66f35f5d31a9860a73307b0bac669515a4460247249cf89fc46b7208fdd8b'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6_freebsd_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.6_linux_amd64.tar.gz'
architecture = 'amd64'
size = 7713771
md5 = '64be2a718f4e2b87ef97e5f8724e8baf'
sha1 = '5705286e67fed0548ec923b89c420601175ff9d1'
sha256 = 'fa5517ff530dae013d33aec1e2d6743405bcbcf0b6ebb52c6a41630330add78b'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6_linux_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.6_darwin_arm64.tar.gz'
architecture = 'arm64'
size = 7137327
md5 = '4d6cb08221ff61390ef5f75a65f47b01'
sha1 = '20b555230c9bde44f1eb3a742e4a7a7dfdc44cad'
sha256 = '811b0ec4f36f47f46eac41d5aab6473703af18643864ece011d21105b98c02f4'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6_darwin_arm64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.6_linux_arm64.tar.gz'
architecture = 'arm64'
size = 6835555
md5 = '119f56f29c29ee92ce5bce1d40118aec'
sha1 = '29a241db3a2fb0ab2f3766873049665bd10a2baa'
sha256 = 'edc0af6a679ac54c9186086d5e39752c1fe03b8356211082ddea6f3164b8d708'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.6/snailmail_0.0.6_linux_arm64.tar.gz'

[[package_version]]
package = 'snailmail'
version = '0.0.9'
state = 'draft'

[[package_version.blob]]
filename = 'snailmail_0.0.9_darwin_amd64.tar.gz'
architecture = 'amd64'
size = 7832904
md5 = 'f32fa10f21d5ef7ac5a5dd9b9776090a'
sha1 = 'e697688e7545fe11c5439a8420231fb9c0716d8b'
sha256 = '2a64a6a1ab9e8d2a2e83bad02381db30e09ec312b70f18b95ee2eded0c0720bd'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9_darwin_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.9_freebsd_amd64.tar.gz'
architecture = 'amd64'
size = 7656201
md5 = '4130b5fd00d98528c6dcc120093c8506'
sha1 = '2eaa810333306075ca67e7fa7f5b5f5e547cbcac'
sha256 = 'aad0f028fc7bdb356a50b2954a2096b10a8217e317806d111ee96ecd94d96cab'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9_freebsd_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.9_linux_amd64.tar.gz'
architecture = 'amd64'
size = 7727953
md5 = 'b1bea20dda05a6429b7d0933144e7342'
sha1 = '011a53c21c930fc371185cf7cc5a7d200ace6694'
sha256 = 'a5a721c545da3c1c33ecaa2f56c5a4d370ef2e4175fcb12781486cf98b089612'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9_linux_amd64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.9_darwin_arm64.tar.gz'
architecture = 'arm64'
size = 7150167
md5 = '511e5c6d4538a4964f750da5a36ae6bf'
sha1 = '2e138e9a743ddd328f26f119738e137ab12b2089'
sha256 = '8472252e16c7630a23fbaa6c43f534d9c906adf08c00d94ad939d4d3930ef526'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9_darwin_arm64.tar.gz'

[[package_version.blob]]
filename = 'snailmail_0.0.9_linux_arm64.tar.gz'
architecture = 'arm64'
size = 6850389
md5 = '1b5bc957926b4271b76e6d674b6188c3'
sha1 = '4b426e8a701b0a1b3e4795efeed3dc3ef3300d6b'
sha256 = 'c226341d63b471c7e8cf025bfcad704660caab18b8e12d7bb2557bb36ab40a12'

[package_version.blob.origin]
kind = 'https'
url = 'https://github.com/shellcell/snailmail/releases/download/v0.0.9/snailmail_0.0.9_linux_arm64.tar.gz'

[[placement]]
package = 'snailmail'
version = '0.0.3'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.5'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.6'
track = 'stable'

[[placement]]
package = 'snailmail'
version = '0.0.9'
track = 'stable'
